server:
  port: 8080
spring:
  application:
    name: accounts
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:file:./h2db
     # Uncomment the following line to use an in-memory database
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true