spring:
  application:
    name: MessagingService

  cloud:
    function:
      definition: email|sms
    stream:
      defaultBinder: kafka
      bindings:
        accountOpening-out-0:
          destination: account-opening-topic
          content-type: application/json
          producer:
            configuration:
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
              value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
              acks: "all"
              retries: 3
              linger.ms: 10
              batch.size: 16384
              compression.type: gzip
              max.block.ms: 5000
              request.timeout.ms: 30000
              enable.idempotence: true
              buffer.memory: 33554432
              max.in.flight.requests.per.connection: 3

        accountOpening-in-0:
          destination: account-opening-topic
          group: ${spring.application.name}
          content-type: application/json
          consumer:
            max-attempts: 3
            auto-offset-reset: earliest
            concurrency: 3
            ack-mode: record
            isolation-level: read_committed
            properties:
              spring.json.trusted.packages: '*'

            retryable-exceptions:
              java.lang.Exception: true
              java.io.IOException: true
              org.springframework.messaging.MessagingException: true
              org.springframework.web.client.RestClientException: true
              org.springframework.web.client.HttpServerErrorException: true
              org.springframework.web.client.ResourceAccessException: true
              org.springframework.kafka.KafkaException: true
              org.apache.kafka.common.errors.TimeoutException: true
              org.apache.kafka.common.errors.RetriableException: true
              org.springframework.kafka.listener.ListenerExecutionFailedException: true

            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            back-off-max-interval: 10000

            enable-dlq: true
            dlq-name: account-opening-dlq
            dlq-binding:
              destination: account-opening-dlq

      
      kafka:
        binder:
          brokers: 10.11.204.202:9092

  rabbitmq:
    host: 10.11.204.202
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s

server:
  port: 9091

logging:
  level:
    com.eazybank: INFO
    com.eazybank.messaging: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG
    org.springframework.integration: DEBUG
