account:
  version: '2.0.0'
  details:
    name: 'DEV'
    description: 'DEV Account Service'
  contact:
    email:
      - 'pagluu@gmail.com'
      - 'dev45@gmail.com'
    phone:
      - '+990129042234'
      - '5662389239'
  products:
    - 'Loan Account'

spring:
  datasource:
    url: jdbc:oracle:thin:@10.11.201.55:1525/ucbldb
    # Uncomment the following line to use an in-memory database
    driverClassName: oracle.jdbc.OracleDriver
    username: 'EMOB'
    password: 'emob'