account:
  version: '3.0.0'
  details:
    name: 'PROD'
    description: 'PROD Account Service'
  contact:
    email:
      - 'dhamaal@gmail.com'
      - 'kalu234@gmail.com'
    phone:
      - '+1210129042234'
      - '9123662389239'
  products:
    - 'Savings Account'
    - 'Current Account'