spring:
  application:
    name: "configserver"

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config/"
          search-locations: "file:///F://Electron"

  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

server:
  port: 8071

