spring:
  application:
    name: "configserver"

  profiles:
    active: native

  rabbitmq:
    host: 10.11.204.202
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config/"
          search-locations: "file:///C://Users//USER//Microservice//config"
          refresh-rate: 30
    bus:
      enabled: true
      refresh:
        enabled: true
  
  
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

server:
  port: 8071

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework.cloud.config: DEBUG
    org.springframework.cloud.bus: DEBUG


management:
  endpoints:
    web:
    exposure:
      include: "*"
  endpoint:
    health:
    show-details: always

