spring:
  application:
    name: "configserver"

  profiles:
    active: native

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          #search-locations: "classpath:/config/"
          search-locations: "file:///F://Electron"
          refresh-rate: 30

  
  security:
    user:
      name: ${CONFIG_SERVER_USERNAME:configuser}
      password: ${CONFIG_SERVER_PASSWORD:configpass}

server:
  port: 8071


