server:
  port: 8090
spring:
  application:
    name: loans
  devtools:
    restart:
      enabled: true
  jpa:
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    #host: host.docker.internal
    host: 10.11.204.202
    port: 5672
    username: guest
    password: guest

  profiles:
    active: dev

  config:
    import: optional:configserver:http://myuser:mypassword@host.docker.internal:8071/


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud: DEBUG
    org.springframework.context: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.rabbit: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

