services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    container_name: accounts_ms
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    volumes:
      - ./accounts/logs:/var/log/accounts
    networks:
      - eazybank_net

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    container_name: loans_ms
    ports:
      - 8090:8090
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    volumes:
      - ./loans/logs:/var/log/loans
    networks:
      - eazybank_net

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    container_name: cards_ms
    ports:
      - 9000:9000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M
        reservations:
          cpus: '0.1'
          memory: 256M
    volumes:
      - ./cards/logs:/var/log/cards
    networks:
      - eazybank_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.8.0
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./accounts/logs:/var/log/accounts:ro
      - ./loans/logs:/var/log/loans:ro
      - ./cards/logs:/var/log/cards:ro
    networks:
      - eazybank_net
    depends_on:
      - accounts
      - loans
      - cards

networks:
  eazybank_net:
    driver: bridge

