server:
  port: 9000
spring:
  application:
    name: cards
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://10.11.200.37:5432/postgres
    # Uncomment the following line to use an in-memory database
    driverClassName: org.postgresql.Driver
    username: 'postgres'
    password: '12345'
    hikari:
      maximum-pool-size: 10
      # Minimum idle connections (default: same as maximum-pool-size)
      minimum-idle: 2
      # Max lifetime of a connection (ms, default: 1800000 = 30 mins)
      max-lifetime: 600000  # 10 mins
      # Timeout for acquiring a connection (ms, default: 30000 = 30s)
      connection-timeout: 10000  # 5s
      # Test connections before giving them to the app (default: false)
      connection-test-query: SELECT 1
      # How long an idle connection stays in the pool (ms, default: 600000 = 10 mins)
      idle-timeout: 300000  # 5 mins
      # Enable leak detection (logs abandoned connections)
      leak-detection-threshold: 5000  # 5s
  jpa:
    #database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8071/"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
